instagram_client_id: d119273d693948dea278436882eb2536
instagram_client_secret: e20f05e3f1eb45a9bd82d1db9ddf97e8
instagram_callback_url: http://localhost:3001/oauth/callback
rekognize_client_id: aupQnDmqKeJAINIk
rekognize_client_secret: iCElJemma1ifWkFa