development:
  adapter: sqlite3
  database: db/db.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/db.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mustachifymeplease-database
  pool: 5
  timeout: 5000